apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
spec:
  type: NodePort
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 5000       # Puerto interno del contenedor
      targetPort: 5000 # Puerto donde corre la app
      nodePort: 30007  # Puerto externo que usar√°s para acceder
